# Generated by Django 4.2.2 on 2023-06-22 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hunter", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hunter",
            name="archiving",
        ),
    ]
