version: "3.7"

services:
  nginx:
    build: ./nginx
    image: 155324383290.dkr.ecr.ap-northeast-2.amazonaws.com/moonblog-nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    links:
      - app
    depends_on:
      - app

  app:
    volumes:
      - static:/static
    image: 155324383290.dkr.ecr.ap-northeast-2.amazonaws.com/moonblog-django
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

volumes:
  static:
