# Generated by Django 4.0.2 on 2022-03-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_tag',
        ),
        migrations.AddField(
            model_name='posttag',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tag_cabinet', to='post.post'),
            preserve_default=False,
        ),
    ]
