# Generated by Django 4.2.2 on 2023-07-06 01:52

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='내용'),
        ),
    ]
