# Generated by Django 4.0.2 on 2022-03-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_post_tag_posttag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.CharField(default='', max_length=255),
        ),
    ]
