# Generated by Django 4.2.2 on 2023-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_created_at_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시판', 'verbose_name_plural': '게시판'},
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.CharField(default='', max_length=255, verbose_name='파일 주소'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
