# Generated by Django 4.0.2 on 2022-03-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('position', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='AchieveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_cabinet', to='achievement.achievement')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.skill')),
            ],
            options={
                'db_table': 'achievement_skill',
            },
        ),
        migrations.CreateModel(
            name='AchieveDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desc_cabinet', to='achievement.achievement')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.description')),
            ],
            options={
                'db_table': 'achievement_desc',
            },
        ),
    ]
