# Generated by Django 4.2.2 on 2023-06-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunter', '0001_initial'),
        ('career', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchieveAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AchieveDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='업적 명')),
                ('start_date', models.DateField(verbose_name='시작날짜')),
                ('end_date', models.DateField(verbose_name='종료날짜')),
                ('position', models.CharField(max_length=50, verbose_name='직책')),
                ('main_work', models.CharField(max_length=100, null=True, verbose_name='주요 업무')),
                ('attachs', models.ManyToManyField(related_name='achievements', through='achievement.AchieveAttach', to='info.attach')),
                ('corp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='career.career', verbose_name='회사')),
                ('descriptions', models.ManyToManyField(related_name='achievements', through='achievement.AchieveDescription', to='info.description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='hunter.hunter', verbose_name='모험가')),
            ],
            options={
                'verbose_name': '업적',
                'verbose_name_plural': '업적',
                'db_table': 'achievement',
            },
        ),
        migrations.CreateModel(
            name='AchieveSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='achievement.achievement')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='skills',
            field=models.ManyToManyField(related_name='achievements', through='achievement.AchieveSkill', to='info.skill'),
        ),
        migrations.AddField(
            model_name='achievedescription',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='achievement.achievement'),
        ),
        migrations.AddField(
            model_name='achievedescription',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.description'),
        ),
        migrations.AddField(
            model_name='achieveattach',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='achievement.achievement'),
        ),
        migrations.AddField(
            model_name='achieveattach',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.attach'),
        ),
    ]
