# Generated by Django 4.0.2 on 2022-03-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('achievement', '0002_achievement_corp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='career.career'),
        ),
    ]
