# Generated by Django 4.0.2 on 2022-03-17 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_file_name'),
        ('achievement', '0003_alter_achievement_corp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchieveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='file_cabinet', to='achievement.achievement')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.skill')),
            ],
        ),
    ]
