# Generated by Django 4.0.2 on 2022-03-17 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0004_achievefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AchieveFile',
        ),
    ]
