# Generated by Django 4.0.2 on 2022-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0006_achievefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='main_work',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
