# Generated by Django 4.2.2 on 2023-06-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_alter_career_options_alter_career_end_date_and_more'),
        ('me', '0004_alter_archiving_options_alter_education_options_and_more'),
        ('achievement', '0009_achievement_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': '업적', 'verbose_name_plural': '업적'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='corp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='career.career', verbose_name='회사'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='end_date',
            field=models.DateField(verbose_name='종료날짜'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='main_work',
            field=models.CharField(max_length=100, null=True, verbose_name='주요 업무'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='업적 명'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='me.me', verbose_name='모험가'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='position',
            field=models.CharField(max_length=50, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='start_date',
            field=models.DateField(verbose_name='시작날짜'),
        ),
    ]
