# Generated by Django 4.2.2 on 2023-06-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('ip', models.CharField(max_length=50, null=True, verbose_name='세계')),
                ('content', models.TextField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '답변',
                'verbose_name_plural': '답변',
            },
        ),
    ]
