# Generated by Django 4.2.2 on 2023-07-01 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pk'], 'verbose_name': '질문', 'verbose_name_plural': '질문'},
        ),
    ]
