# Generated by Django 4.2.2 on 2023-06-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_question_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='answer',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
