# Generated by Django 4.2.2 on 2023-06-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hunter', '0001_initial'),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='길드명')),
                ('position', models.CharField(max_length=50, verbose_name='직책')),
                ('work', models.CharField(max_length=50, verbose_name='맡은 일')),
                ('start_date', models.DateField(verbose_name='시작날짜')),
                ('end_date', models.DateField(verbose_name='종료날짜')),
            ],
            options={
                'verbose_name': '길드',
                'verbose_name_plural': '길드',
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.skill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerAttach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('attach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.attach')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='career',
            name='attachs',
            field=models.ManyToManyField(related_name='careers', through='career.CareerAttach', to='info.attach'),
        ),
        migrations.AddField(
            model_name='career',
            name='descriptions',
            field=models.ManyToManyField(related_name='careers', through='career.CareerDescription', to='info.description'),
        ),
        migrations.AddField(
            model_name='career',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='hunter.hunter', verbose_name='모험가'),
        ),
        migrations.AddField(
            model_name='career',
            name='skills',
            field=models.ManyToManyField(related_name='careers', through='career.CareerSkill', to='info.skill'),
        ),
    ]
