# Generated by Django 4.0.2 on 2022-03-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'career',
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_cabinet', to='career.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.skill')),
            ],
            options={
                'db_table': 'career_skill',
            },
        ),
        migrations.CreateModel(
            name='CareerDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc_cabinet', to='career.career')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.description')),
            ],
            options={
                'db_table': 'career_desc',
            },
        ),
    ]
