# Generated by Django 4.2.2 on 2023-07-06 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_career_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'ordering': ['-id'], 'verbose_name': '길드', 'verbose_name_plural': '길드'},
        ),
    ]
