# Generated by Django 4.2.2 on 2023-06-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_rename_loc_me_address_archdesc_created_and_more'),
        ('career', '0002_career_created_career_deleted_career_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='me.me'),
            preserve_default=False,
        ),
    ]
