# Generated by Django 4.2.2 on 2023-06-21 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_alter_archiving_options_alter_education_options_and_more'),
        ('career', '0003_career_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='career',
            options={'verbose_name': '길드', 'verbose_name_plural': '길드'},
        ),
        migrations.AlterField(
            model_name='career',
            name='end_date',
            field=models.DateField(verbose_name='종료날짜'),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=50, verbose_name='길드명'),
        ),
        migrations.AlterField(
            model_name='career',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='me.me', verbose_name='모험가'),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.CharField(max_length=50, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='career',
            name='start_date',
            field=models.DateField(verbose_name='시작날짜'),
        ),
        migrations.AlterField(
            model_name='career',
            name='work',
            field=models.CharField(max_length=50, verbose_name='맡은 일'),
        ),
    ]
