# Generated by Django 4.2.2 on 2023-06-22 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attach",
            options={"verbose_name": "첨부파일", "verbose_name_plural": "첨부파일"},
        ),
    ]
