# Generated by Django 4.2.2 on 2023-06-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_attach_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('B', 'BackEnd'), ('D', 'Database'), ('F', 'FrontEnd'), ('I', 'Infra'), ('C', 'Communication'), ('L', 'Language'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='스킬 계통'),
        ),
    ]
