# Generated by Django 4.0.2 on 2022-03-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
