# Generated by Django 4.2.2 on 2023-06-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_description_created_description_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'verbose_name': '상세내용', 'verbose_name_plural': '상세내용'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': '스킬', 'verbose_name_plural': '스킬'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('B', 'BackEnd'), ('F', 'FrontEnd'), ('D', 'DevOps'), ('I', 'Infra'), ('C', 'Communication'), ('L', 'Language'), ('U', 'Unknown')], default='U', max_length=1, verbose_name='스킬 계통'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='Unknown Skill', max_length=20, verbose_name='스킬 이름'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='태그이름'),
        ),
    ]
