# Generated by Django 4.0.2 on 2022-03-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dungeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='정의되지 않은 던전', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Soso'), (3, 'Normal'), (4, 'Hard'), (5, 'Hell')])),
                ('size', models.CharField(max_length=20)),
                ('loc', models.CharField(max_length=50)),
                ('impression', models.TextField()),
            ],
            options={
                'db_table': 'dungeon',
            },
        ),
        migrations.CreateModel(
            name='DungeonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='skill_cabinet', to='dungeon.dungeon')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.skill')),
            ],
            options={
                'db_table': 'dungeon_skill',
            },
        ),
        migrations.CreateModel(
            name='DungeonDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.description')),
                ('dungeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desc_cabinet', to='dungeon.dungeon')),
            ],
            options={
                'db_table': 'dungeon_desc',
            },
        ),
    ]
