# Generated by Django 4.2.2 on 2023-06-21 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_rename_loc_me_address_archdesc_created_and_more'),
        ('dungeon', '0002_dungeon_created_dungeon_deleted_dungeon_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeon',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dungeons', to='me.me'),
            preserve_default=False,
        ),
    ]
