# Generated by Django 4.0.2 on 2022-03-15 07:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'archiving',
            },
        ),
        migrations.CreateModel(
            name='Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='00000000000', max_length=12)),
                ('birth', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('edu', models.CharField(default='', max_length=100)),
                ('loc', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table': 'me',
            },
        ),
        migrations.CreateModel(
            name='MySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_skill', to='me.me')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.skill')),
            ],
            options={
                'db_table': 'my_skill',
            },
        ),
        migrations.CreateModel(
            name='MyDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='descs', to='info.description')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desc_cabinet', related_query_name='desc_cabinets', to='me.me')),
            ],
            options={
                'db_table': 'my_desc',
            },
        ),
        migrations.CreateModel(
            name='ArchDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archiving', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='me.archiving')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='info.description')),
            ],
            options={
                'db_table': 'arch_desc',
            },
        ),
    ]
