# Generated by Django 4.0.2 on 2022-03-23 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archdesc',
            name='archiving',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desc_cabinet', to='me.archiving'),
        ),
    ]
