# Generated by Django 4.2.2 on 2023-06-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_alter_archiving_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name': '모험가', 'verbose_name_plural': '모험가'},
        ),
        migrations.AlterField(
            model_name='archiving',
            name='category',
            field=models.CharField(max_length=20, verbose_name='주제명'),
        ),
        migrations.AlterField(
            model_name='archiving',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivings', to='me.me', verbose_name='모험가'),
        ),
        migrations.AlterField(
            model_name='education',
            name='ended',
            field=models.DateField(blank=True, null=True, verbose_name='종료날짜'),
        ),
        migrations.AlterField(
            model_name='education',
            name='full_point',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='전체학점'),
        ),
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=50, verbose_name='전공'),
        ),
        migrations.AlterField(
            model_name='education',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='educations', to='me.me', verbose_name='모험가'),
        ),
        migrations.AlterField(
            model_name='education',
            name='name',
            field=models.CharField(max_length=50, verbose_name='훈련장명'),
        ),
        migrations.AlterField(
            model_name='education',
            name='point',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='학점'),
        ),
        migrations.AlterField(
            model_name='education',
            name='started',
            field=models.DateField(verbose_name='시작날짜'),
        ),
        migrations.AlterField(
            model_name='me',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='me',
            name='birth',
            field=models.DateField(verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='me',
            name='edu',
            field=models.CharField(default='', max_length=100, verbose_name='학력'),
        ),
        migrations.AlterField(
            model_name='me',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='me',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='me',
            name='phone',
            field=models.CharField(default='00000000000', max_length=12, verbose_name='연락처'),
        ),
    ]
